"""
presets.py
──────────────────────────────────────────────────────────────────────────
Banco de presets do "Kit de Intenção Visual".

Cada preset descreve completamente um estilo visual e sonoro:

    keywords        : list[str]  — Palavras-gatilho (pt/en) para detecção automática.
    nome            : str        — Nome de exibição do estilo.
    emocao          : str        — Descrição emocional ("Palavra · Palavra · Palavra").
    paleta          : list[str]  — 4 cores hex usadas nos cards e HUD.
    glow            : str        — Cor de destaque/acento (HUD, luz-chave do MiniPlayer).
    bg              : list[str]  — 3 cores hex do gradiente do céu (base → meio → topo).
    tipografia      : str        — Nome da fonte de exibição.
    ritmo           : str        — "N cortes/min".
    bpm             : int        — Batidas por minuto.
    iluminacao      : str        — Descrição textual da iluminação.
    enquadramento   : str        — Plano principal (mantido por compatibilidade).
    cenas           : list[dict] — [{"cam": ..., "desc": ...}] para o MiniPlayer3D.
    audio           : dict       — Configurações de áudio:
        tipo        : str        — Família do motor Tone.js (ver abaixo).
        descricao   : str        — Descrição textual.
        efeito      : str        — Efeito narrativo/psicológico pretendido.

Famílias de áudio disponíveis (motor Tone.js):
    trap · cyberpunk · romance · noir · epic · lofi · ambient · rock · festa · eletronica
"""

# ── Conjuntos de câmera reutilizáveis ────────────────────────────────────────
# Rótulos reconhecidos pelo MiniPlayer3D para enquadramento específico:
#   'Close extremo' / 'Macro extremo' / 'Ângulo baixo' /
#   'Plano aberto' / 'Grande angular' / 'Travelling lateral'
# Qualquer outro rótulo recebe enquadramento genérico.

CENAS_ALTA_ENERGIA = [
    {"cam": "Travelling lateral", "desc": "Movimento lateral acompanha o pulso da cena"},
    {"cam": "Close extremo",      "desc": "Detalhe abrupto no pico de energia"},
    {"cam": "Ângulo baixo",       "desc": "Câmera baixa amplia a potência"},
    {"cam": "Grande angular",     "desc": "Abertura total para o impacto"},
]

CENAS_TENSO = [
    {"cam": "Plano aberto",       "desc": "Silêncio visual antes da virada"},
    {"cam": "Close extremo",      "desc": "Olhar fixo, tensão crescente"},
    {"cam": "Ângulo baixo",       "desc": "Presença que ameaça o quadro"},
    {"cam": "Travelling lateral", "desc": "Deslocamento sutil, vigilância constante"},
]

CENAS_EPICO = [
    {"cam": "Grande angular",     "desc": "Escala monumental do cenário"},
    {"cam": "Ângulo baixo",       "desc": "Heroísmo e domínio do quadro"},
    {"cam": "Plano aberto",       "desc": "Vastidão antes do clímax"},
    {"cam": "Close extremo",      "desc": "Detalhe que carrega peso histórico"},
]

CENAS_INTIMISTA = [
    {"cam": "Plano aberto",       "desc": "Respiro suave da cena"},
    {"cam": "Close extremo",      "desc": "Proximidade emocional"},
    {"cam": "Travelling lateral", "desc": "Deslize delicado, quase imóvel"},
]

CENAS_CONTEMPLATIVO = [
    {"cam": "Plano aberto",       "desc": "Tempo desacelerado"},
    {"cam": "Travelling lateral", "desc": "Deriva lenta e constante"},
    {"cam": "Close extremo",      "desc": "Pequeno detalhe, grande significado"},
]

CENAS_COMERCIAL = [
    {"cam": "Close extremo",      "desc": "Textura e acabamento em destaque"},
    {"cam": "Travelling lateral", "desc": "Giro de apresentação do produto"},
    {"cam": "Plano aberto",       "desc": "Contexto de uso real"},
    {"cam": "Ângulo baixo",       "desc": "Valorização do objeto"},
]


PRESETS = {

    # ════════════════════════════════════════════════════════════════
    # PRESETS ORIGINAIS
    # ════════════════════════════════════════════════════════════════

    "blade": {
        "keywords": ["blade", "cyberpunk", "neon", "futurista", "tech", "matrix"],
        "nome": "Cyberpunk",
        "emocao": "Tensão · Adrenalina · Desorientação",
        "paleta": ["#0a0a0f", "#00fff7", "#7c3aed", "#ff006e"],
        "glow": "#00fff7",
        "bg": ["#0a0a0f", "#120a24", "#1a0a2e"],
        "tipografia": "Rajdhani Bold",
        "ritmo": "32 cortes/min",
        "bpm": 140,
        "iluminacao": "Neon lateral · Chuva de luz",
        "enquadramento": "Close extremo",
        "cenas": CENAS_ALTA_ENERGIA,
        "audio": {"tipo": "cyberpunk", "descricao": "Sintetizador metálico + glitch eletrônico", "efeito": "Gera tensão e adrenalina"},
    },
    "poder": {
        "keywords": ["poder", "urgência", "força", "luxo", "cartier", "sdm", "rap", "trap", "gold", "luxury", "power"],
        "nome": "Luxo Cinematográfico",
        "emocao": "Poder · Status · Inevitabilidade",
        "paleta": ["#0d0500", "#8B3A00", "#C8860A", "#F5D78E"],
        "glow": "#C8860A",
        "bg": ["#0d0500", "#2a1500", "#4a2800"],
        "tipografia": "Montserrat Black",
        "ritmo": "22 cortes/min",
        "bpm": 95,
        "iluminacao": "Tungstênio quente · Sombra épica",
        "enquadramento": "Ângulo baixo",
        "cenas": CENAS_EPICO,
        "audio": {"tipo": "trap", "descricao": "Kick 808 grave + hi-hat seco", "efeito": "Ativa sensação de poder"},
    },
    "romance": {
        "keywords": ["romance", "amor", "suave", "delicado", "intimidade", "saudade", "love", "soft"],
        "nome": "Romance Etéreo",
        "emocao": "Nostalgia · Vulnerabilidade · Conexão",
        "paleta": ["#1a0010", "#8B0050", "#FF6B9D", "#FFD6E8"],
        "glow": "#FF6B9D",
        "bg": ["#1a0010", "#3a0030", "#5a1050"],
        "tipografia": "Cormorant Garamond",
        "ritmo": "12 cortes/min",
        "bpm": 72,
        "iluminacao": "Luz difusa · Bokeh profundo",
        "enquadramento": "Plano aberto",
        "cenas": CENAS_INTIMISTA,
        "audio": {"tipo": "romance", "descricao": "Pad suave + melodia de piano", "efeito": "Ativa oxitocina"},
    },
    "misterio": {
        "keywords": ["mistério", "sombrio", "dark", "noir", "suspense", "thriller", "crime", "mystery"],
        "nome": "Noir Contemporâneo",
        "emocao": "Ansiedade · Fascínio · Perigo",
        "paleta": ["#000000", "#0a0a0a", "#1a1a2e", "#4a4a6a"],
        "glow": "#4a4a6a",
        "bg": ["#000000", "#0a0a0a", "#1a1a2e"],
        "tipografia": "Playfair Display",
        "ritmo": "18 cortes/min",
        "bpm": 85,
        "iluminacao": "Contraluz duro · Sombra absoluta",
        "enquadramento": "Plano médio",
        "cenas": CENAS_TENSO,
        "audio": {"tipo": "noir", "descricao": "Baixo profundo + silêncio dramático", "efeito": "Ativa amígdala"},
    },
    "epico": {
        "keywords": ["épico", "guerra", "batalha", "herói", "dune", "grandioso", "histórico", "epic", "war", "hero"],
        "nome": "Épico Cinematográfico",
        "emocao": "Grandiosidade · Sacrifício · Destino",
        "paleta": ["#0a0500", "#3d1a00", "#8B4513", "#DAA520"],
        "glow": "#DAA520",
        "bg": ["#0a0500", "#2a1000", "#4a2000"],
        "tipografia": "Cinzel Bold",
        "ritmo": "18 cortes/min",
        "bpm": 88,
        "iluminacao": "Luz épica lateral · Névoa dramática",
        "enquadramento": "Grande angular",
        "cenas": CENAS_EPICO,
        "audio": {"tipo": "epic", "descricao": "Orquestra + percussão épica", "efeito": "Grandiosidade"},
    },
    "minimalista": {
        "keywords": ["minimalista", "clean", "simples", "moderno", "elegante", "corporativo", "minimal", "simple", "modern"],
        "nome": "Minimalismo Moderno",
        "emocao": "Clareza · Confiança · Sofisticação",
        "paleta": ["#ffffff", "#f5f5f5", "#333333", "#000000"],
        "glow": "#999999",
        "bg": ["#1a1a1a", "#3a3a3a", "#5a5a5a"],
        "tipografia": "Helvetica Neue Light",
        "ritmo": "15 cortes/min",
        "bpm": 80,
        "iluminacao": "Luz difusa branca · Alto key",
        "enquadramento": "Plano médio",
        "cenas": CENAS_COMERCIAL,
        "audio": {"tipo": "ambient", "descricao": "Piano minimalista + silêncio", "efeito": "Clareza e foco"},
    },
    "lofi": {
        "keywords": ["lo-fi", "lofi", "chill", "relaxar", "estudo", "café", "vibe"],
        "nome": "Lo-Fi Nostálgico",
        "emocao": "Calma · Nostalgia · Introspecção",
        "paleta": ["#2d1f3d", "#7c5cbf", "#c9a0dc", "#f0e6ff"],
        "glow": "#c9a0dc",
        "bg": ["#2d1f3d", "#4a3560", "#7c5cbf"],
        "tipografia": "IBM Plex Mono",
        "ritmo": "8 cortes/min",
        "bpm": 75,
        "iluminacao": "Luz de abajur quente",
        "enquadramento": "Plano médio",
        "cenas": CENAS_CONTEMPLATIVO,
        "audio": {"tipo": "lofi", "descricao": "Beats de baixa fidelidade", "efeito": "Relaxamento e foco"},
    },
    "horror": {
        "keywords": ["horror", "terror", "medo", "assombrado", "ghost", "paranormal"],
        "nome": "Horror Psicológico",
        "emocao": "Medo · Paranoia · Desespero",
        "paleta": ["#000000", "#1a0000", "#8B0000", "#ff0000"],
        "glow": "#ff0000",
        "bg": ["#000000", "#1a0000", "#330000"],
        "tipografia": "Creepster",
        "ritmo": "25 cortes/min",
        "bpm": 120,
        "iluminacao": "Luz vermelha lateral · Escuridão total",
        "enquadramento": "Close extremo",
        "cenas": CENAS_TENSO,
        "audio": {"tipo": "noir", "descricao": "Strings tensas + batida cardíaca", "efeito": "Ativa medo máximo"},
    },
    "retro80": {
        "keywords": ["retrô", "80s", "synthwave", "vaporwave", "anos 80", "outrun"],
        "nome": "Synthwave Retrô",
        "emocao": "Nostalgia · Energia · Escapismo",
        "paleta": ["#0d0221", "#f72585", "#7209b7", "#4cc9f0"],
        "glow": "#4cc9f0",
        "bg": ["#0d0221", "#3a0a4a", "#7209b7"],
        "tipografia": "Press Start 2P",
        "ritmo": "24 cortes/min",
        "bpm": 118,
        "iluminacao": "Grade neon · Pôr do sol gradiente",
        "enquadramento": "Plano aberto",
        "cenas": CENAS_ALTA_ENERGIA,
        "audio": {"tipo": "cyberpunk", "descricao": "Synth vintage + drum machine", "efeito": "Nostalgia e energia retrô"},
    },
    "natureza": {
        "keywords": ["natureza", "floresta", "cachoeira", "selva", "forest", "waterfall"],
        "nome": "Natureza Selvagem",
        "emocao": "Liberdade · Paz · Grandiosidade",
        "paleta": ["#0a1f0a", "#1a4a1a", "#2d8a2d", "#7ddf64"],
        "glow": "#7ddf64",
        "bg": ["#0a1f0a", "#1a4a1a", "#3d6a3d"],
        "tipografia": "Libre Baskerville",
        "ritmo": "10 cortes/min",
        "bpm": 65,
        "iluminacao": "Luz natural filtrada",
        "enquadramento": "Grande angular",
        "cenas": CENAS_CONTEMPLATIVO,
        "audio": {"tipo": "ambient", "descricao": "Sons da natureza + melodia orgânica", "efeito": "Paz e redução de estresse"},
    },
    "scifi": {
        "keywords": ["ficção científica", "sci-fi", "espaço", "space", "galáxia", "alienígena"],
        "nome": "Sci-Fi Espacial",
        "emocao": "Maravilha · Solidão · Infinito",
        "paleta": ["#000814", "#001d3d", "#003566", "#ffd60a"],
        "glow": "#ffd60a",
        "bg": ["#000814", "#001d3d", "#003566"],
        "tipografia": "Exo 2 Bold",
        "ritmo": "20 cortes/min",
        "bpm": 90,
        "iluminacao": "Luz de estrelas · Bioluminescência",
        "enquadramento": "Grande angular",
        "cenas": CENAS_EPICO,
        "audio": {"tipo": "ambient", "descricao": "Ambient espacial + sintetizador", "efeito": "Maravilha e imensidão"},
    },
    "sport": {
        "keywords": ["esporte", "sport", "futebol", "corrida", "atletismo", "vitória"],
        "nome": "Sport Motion",
        "emocao": "Adrenalina · Vitória · Superação",
        "paleta": ["#000000", "#1a1a1a", "#ff4d00", "#ffffff"],
        "glow": "#ff4d00",
        "bg": ["#000000", "#1a1a1a", "#3a2000"],
        "tipografia": "Bebas Neue",
        "ritmo": "35 cortes/min",
        "bpm": 145,
        "iluminacao": "Luz de estádio · Slow motion dramático",
        "enquadramento": "Ângulo baixo",
        "cenas": CENAS_ALTA_ENERGIA,
        "audio": {"tipo": "trap", "descricao": "Trap acelerado + crowd noise", "efeito": "Adrenalina e superação"},
    },
    "fashion": {
        "keywords": ["moda", "fashion", "passarela", "vogue", "editorial", "estilo"],
        "nome": "Fashion Editorial",
        "emocao": "Poder Feminino · Arte · Atitude",
        "paleta": ["#f5f5f5", "#1a1a1a", "#c9b99a", "#8B7355"],
        "glow": "#c9b99a",
        "bg": ["#1a1a1a", "#2d2d2d", "#4a4a4a"],
        "tipografia": "Bodoni Moda",
        "ritmo": "20 cortes/min",
        "bpm": 92,
        "iluminacao": "Luz de estúdio · High fashion",
        "enquadramento": "Plano médio",
        "cenas": CENAS_COMERCIAL,
        "audio": {"tipo": "eletronica", "descricao": "Electronic fashion + deep bass", "efeito": "Poder e atitude"},
    },
    "travel": {
        "keywords": ["viagem", "travel", "aventura", "explore", "wanderlust", "mochileiro"],
        "nome": "Travel Cinematic",
        "emocao": "Liberdade · Descoberta · Aventura",
        "paleta": ["#003049", "#fcbf49", "#eae2b7", "#f77f00"],
        "glow": "#fcbf49",
        "bg": ["#003049", "#1c5a73", "#f77f00"],
        "tipografia": "Raleway Bold",
        "ritmo": "16 cortes/min",
        "bpm": 84,
        "iluminacao": "Golden hour · Luz natural intensa",
        "enquadramento": "Grande angular",
        "cenas": CENAS_CONTEMPLATIVO,
        "audio": {"tipo": "festa", "descricao": "World music + percussão étnica", "efeito": "Ansiedade por descoberta"},
    },
    "kpop": {
        "keywords": ["k-pop", "kpop", "coreano", "k-drama", "hallyu"],
        "nome": "K-Pop Hyper",
        "emocao": "Energia · Perfeição · Impacto",
        "paleta": ["#ff006e", "#8338ec", "#3a86ff", "#ffbe0b"],
        "glow": "#ffbe0b",
        "bg": ["#1a0a2e", "#3a1a5e", "#8338ec"],
        "tipografia": "Nanum Gothic Bold",
        "ritmo": "40 cortes/min",
        "bpm": 155,
        "iluminacao": "RGB strobo · Holográfico",
        "enquadramento": "Close extremo",
        "cenas": CENAS_ALTA_ENERGIA,
        "audio": {"tipo": "eletronica", "descricao": "Hyperpop + 808 coreano", "efeito": "Energia explosiva"},
    },
    "gothic": {
        "keywords": ["gótico", "gothic", "vampiro", "cemitério", "dark romance", "medieval"],
        "nome": "Dark Gothic",
        "emocao": "Beleza Sombria · Eternidade · Mistério",
        "paleta": ["#0d0014", "#2d1b4e", "#7b2d8b", "#c77dff"],
        "glow": "#c77dff",
        "bg": ["#0d0014", "#1d0a2e", "#2d1b4e"],
        "tipografia": "Cinzel Decorative",
        "ritmo": "16 cortes/min",
        "bpm": 78,
        "iluminacao": "Velas · Luz de lua · Névoa",
        "enquadramento": "Plano médio",
        "cenas": CENAS_TENSO,
        "audio": {"tipo": "noir", "descricao": "Órgão de catedral + violinos", "efeito": "Beleza sombria"},
    },
    "rave": {
        "keywords": ["rave", "festival", "eletrônica", "dj", "club", "techno"],
        "nome": "Rave Underground",
        "emocao": "Êxtase · Libertação · Comunidade",
        "paleta": ["#000000", "#39ff14", "#ff00ff", "#00ffff"],
        "glow": "#ff00ff",
        "bg": ["#000000", "#0a0a0a", "#1a0a2a"],
        "tipografia": "Chakra Petch Bold",
        "ritmo": "45 cortes/min",
        "bpm": 160,
        "iluminacao": "Strobo · Laser · Fumaça",
        "enquadramento": "Grande angular",
        "cenas": CENAS_ALTA_ENERGIA,
        "audio": {"tipo": "eletronica", "descricao": "Techno acelerado 160bpm", "efeito": "Êxtase e libertação"},
    },
    "wedding": {
        "keywords": ["casamento", "wedding", "noiva", "noivo", "amor eterno"],
        "nome": "Casamento Cinematográfico",
        "emocao": "Amor Eterno · Alegria · Emoção",
        "paleta": ["#fff5f5", "#f9dcc4", "#fcd5ce", "#ffffff"],
        "glow": "#fcd5ce",
        "bg": ["#3a2a2a", "#7a5a4a", "#f9dcc4"],
        "tipografia": "Great Vibes",
        "ritmo": "10 cortes/min",
        "bpm": 68,
        "iluminacao": "Golden hour · Luz difusa romântica",
        "enquadramento": "Plano aberto",
        "cenas": CENAS_INTIMISTA,
        "audio": {"tipo": "romance", "descricao": "Piano clássico + cordas suaves", "efeito": "Amor e emoção profunda"},
    },
    "hiphop": {
        "keywords": ["hip-hop", "hiphop", "rap", "street", "urbano", "graffiti"],
        "nome": "Hip-Hop Urbano",
        "emocao": "Autenticidade · Atitude · Flow",
        "paleta": ["#1a1a1a", "#333333", "#ff6b00", "#ffffff"],
        "glow": "#ff6b00",
        "bg": ["#1a1a1a", "#2a2a2a", "#3a2a1a"],
        "tipografia": "Anton",
        "ritmo": "26 cortes/min",
        "bpm": 95,
        "iluminacao": "Luz de rua · Néon urbano",
        "enquadramento": "Ângulo baixo",
        "cenas": CENAS_ALTA_ENERGIA,
        "audio": {"tipo": "trap", "descricao": "Boom bap + scratching", "efeito": "Autenticidade e flow"},
    },
    "underwater": {
        "keywords": ["submarino", "underwater", "oceano", "mergulho", "coral", "profundezas"],
        "nome": "Submersão Profunda",
        "emocao": "Mistério · Silêncio · Profundidade",
        "paleta": ["#03045e", "#0077b6", "#00b4d8", "#90e0ef"],
        "glow": "#00b4d8",
        "bg": ["#03045e", "#0077b6", "#00b4d8"],
        "tipografia": "Josefin Sans Light",
        "ritmo": "8 cortes/min",
        "bpm": 60,
        "iluminacao": "Luz filtrada pela água",
        "enquadramento": "Plano aberto",
        "cenas": CENAS_CONTEMPLATIVO,
        "audio": {"tipo": "ambient", "descricao": "Ambient aquático + low bass", "efeito": "Calma e mistério"},
    },
    "anime": {
        "keywords": ["anime", "mangá", "japonês", "sakura", "katana", "samurai"],
        "nome": "Anime Cinematográfico",
        "emocao": "Intensidade · Honra · Beleza",
        "paleta": ["#1a0a2e", "#c9184a", "#ff758c", "#ffd6e0"],
        "glow": "#ff758c",
        "bg": ["#1a0a2e", "#3a1a3e", "#c9184a"],
        "tipografia": "Noto Sans JP Bold",
        "ritmo": "28 cortes/min",
        "bpm": 130,
        "iluminacao": "Luz dura lateral · Pétalas de sakura",
        "enquadramento": "Close extremo",
        "cenas": CENAS_EPICO,
        "audio": {"tipo": "epic", "descricao": "Orchestral japonês + shamisen", "efeito": "Intensidade e honra"},
    },
    "jazz": {
        "keywords": ["jazz", "blues", "improviso", "sax", "trompete", "clube de jazz"],
        "nome": "Jazz Club",
        "emocao": "Sofisticação · Improviso · Alma",
        "paleta": ["#1a0f00", "#4a2800", "#8B5E3C", "#F4D03F"],
        "glow": "#F4D03F",
        "bg": ["#1a0f00", "#2a1a00", "#4a2800"],
        "tipografia": "Abril Fatface",
        "ritmo": "10 cortes/min",
        "bpm": 72,
        "iluminacao": "Spot light de palco · Fumaça de clube",
        "enquadramento": "Plano médio",
        "cenas": CENAS_INTIMISTA,
        "audio": {"tipo": "lofi", "descricao": "Sax ao vivo + contrabaixo", "efeito": "Sofisticação e alma"},
    },
    "gaming": {
        "keywords": ["gaming", "gamer", "esports", "streamer", "videogame"],
        "nome": "Gaming Cinematic",
        "emocao": "Competição · Foco · Vitória",
        "paleta": ["#0d0d0d", "#39ff14", "#ff00ff", "#0080ff"],
        "glow": "#39ff14",
        "bg": ["#0d0d0d", "#1a0d1a", "#1a0d2a"],
        "tipografia": "Rajdhani Bold",
        "ritmo": "30 cortes/min",
        "bpm": 132,
        "iluminacao": "RGB de setup · Monitor glow",
        "enquadramento": "Close extremo",
        "cenas": CENAS_ALTA_ENERGIA,
        "audio": {"tipo": "eletronica", "descricao": "Chiptune + EDM de arena", "efeito": "Adrenalina competitiva"},
    },
    "spiritual": {
        "keywords": ["espiritual", "spiritual", "transcendência", "divino", "cosmos", "energia"],
        "nome": "Transcendência Espiritual",
        "emocao": "Paz Profunda · Infinito · Conexão",
        "paleta": ["#fff8dc", "#ffd700", "#daa520", "#b8860b"],
        "glow": "#ffd700",
        "bg": ["#2a2410", "#5a4a20", "#b8860b"],
        "tipografia": "IM Fell English Italic",
        "ritmo": "6 cortes/min",
        "bpm": 58,
        "iluminacao": "Luz celestial · Raios divinos",
        "enquadramento": "Grande angular",
        "cenas": CENAS_CONTEMPLATIVO,
        "audio": {"tipo": "ambient", "descricao": "Gregoriano + singing bowls", "efeito": "Transcendência"},
    },
    "foodporn": {
        "keywords": ["gastronomia", "food", "restaurante", "chef", "culinária", "comida"],
        "nome": "Gastronomia Cinematográfica",
        "emocao": "Prazer · Sofisticação · Desejo",
        "paleta": ["#1a0a00", "#4a2800", "#8B5E3C", "#F4A261"],
        "glow": "#F4A261",
        "bg": ["#1a0a00", "#2a1500", "#4a2800"],
        "tipografia": "Playfair Display Italic",
        "ritmo": "12 cortes/min",
        "bpm": 70,
        "iluminacao": "Luz lateral quente · Vapor",
        "enquadramento": "Macro extremo",
        "cenas": CENAS_COMERCIAL,
        "audio": {"tipo": "lofi", "descricao": "Jazz suave + ambiente", "efeito": "Apetite e sofisticação"},
    },
    "documentary": {
        "keywords": ["documentário", "documentary", "jornalismo", "verdade", "real"],
        "nome": "Documentário Realista",
        "emocao": "Verdade · Urgência · Empatia",
        "paleta": ["#2c2c2c", "#4a4a4a", "#888888", "#cccccc"],
        "glow": "#888888",
        "bg": ["#1a1a1a", "#2c2c2c", "#4a4a4a"],
        "tipografia": "Roboto Condensed",
        "ritmo": "14 cortes/min",
        "bpm": 78,
        "iluminacao": "Luz natural · Sem fill",
        "enquadramento": "Plano médio",
        "cenas": CENAS_CONTEMPLATIVO,
        "audio": {"tipo": "ambient", "descricao": "Ambient + narração grave", "efeito": "Credibilidade e emoção real"},
    },
    "luxury_car": {
        "keywords": ["supercar", "lamborghini", "ferrari", "porsche", "carro de luxo"],
        "nome": "Supercar Cinematic",
        "emocao": "Velocidade · Poder · Exclusividade",
        "paleta": ["#1a1a1a", "#8B0000", "#cc0000", "#ff4444"],
        "glow": "#ff4444",
        "bg": ["#1a1a1a", "#2a0a0a", "#3a0000"],
        "tipografia": "Formula1 Bold",
        "ritmo": "30 cortes/min",
        "bpm": 128,
        "iluminacao": "Luz de estúdio · Reflexo de carroceria",
        "enquadramento": "Macro extremo",
        "cenas": CENAS_ALTA_ENERGIA,
        "audio": {"tipo": "trap", "descricao": "Rugido de motor + bass drop", "efeito": "Velocidade e exclusividade"},
    },
    "perfume": {
        "keywords": ["perfume", "fragrance", "luxo árabe", "dubai", "oud", "essência"],
        "nome": "Luxury Fragrance",
        "emocao": "Sensualidade · Exclusividade · Mistério",
        "paleta": ["#1a0a00", "#4a2800", "#C8860A", "#F5D78E"],
        "glow": "#F5D78E",
        "bg": ["#1a0a00", "#2a1500", "#4a2800"],
        "tipografia": "Cormorant Garamond Italic",
        "ritmo": "10 cortes/min",
        "bpm": 66,
        "iluminacao": "Luz de cristal · Reflexo de frasco",
        "enquadramento": "Macro extremo",
        "cenas": CENAS_INTIMISTA,
        "audio": {"tipo": "romance", "descricao": "Oud árabe + silêncio dramático", "efeito": "Sensualidade e exclusividade"},
    },
    "luxury_watch": {
        "keywords": ["relógio de luxo", "rolex", "patek", "audemars", "horlogerie"],
        "nome": "Horology Luxury",
        "emocao": "Precisão · Eternidade · Status",
        "paleta": ["#1a0800", "#4a2800", "#C8860A", "#F5D78E"],
        "glow": "#C8860A",
        "bg": ["#1a0800", "#2a1500", "#4a2800"],
        "tipografia": "Didot Bold",
        "ritmo": "8 cortes/min",
        "bpm": 60,
        "iluminacao": "Luz de joalheria lateral",
        "enquadramento": "Macro extremo",
        "cenas": CENAS_COMERCIAL,
        "audio": {"tipo": "romance", "descricao": "Piano clássico + silêncio preciso", "efeito": "Precisão e eternidade"},
    },
    "drone": {
        "keywords": ["drone", "aéreo", "aerial", "topo", "altitude", "cinematografia aérea"],
        "nome": "Aerial Cinematic",
        "emocao": "Grandeza · Perspectiva · Silêncio",
        "paleta": ["#87CEEB", "#4682B4", "#1E3A5F", "#F0F8FF"],
        "glow": "#F0F8FF",
        "bg": ["#1E3A5F", "#4682B4", "#87CEEB"],
        "tipografia": "Raleway Light",
        "ritmo": "8 cortes/min",
        "bpm": 65,
        "iluminacao": "Luz natural aérea · Golden hour",
        "enquadramento": "Grande angular",
        "cenas": CENAS_EPICO,
        "audio": {"tipo": "ambient", "descricao": "Ambient orquestral + silêncio", "efeito": "Grandeza e perspectiva"},
    },
    "abstract": {
        "keywords": ["abstrato", "abstract", "arte", "experimental", "glitch art"],
        "nome": "Arte Abstrata",
        "emocao": "Criatividade · Caos · Liberdade",
        "paleta": ["#ff0080", "#00ff80", "#0080ff", "#ff8000"],
        "glow": "#00ff80",
        "bg": ["#0a0a0a", "#1a0a1a", "#1a0a2a"],
        "tipografia": "Space Mono Bold",
        "ritmo": "20 cortes/min",
        "bpm": 100,
        "iluminacao": "RGB puro · Projeção mapeada",
        "enquadramento": "Close extremo",
        "cenas": CENAS_ALTA_ENERGIA,
        "audio": {"tipo": "eletronica", "descricao": "Noise experimental + beats quebrados", "efeito": "Criatividade e caos"},
    },
    "ai_tech": {
        "keywords": ["ai", "inteligência artificial", "machine learning", "robot", "tech futurista"],
        "nome": "AI Awakening",
        "emocao": "Fascínio · Medo · Transcendência",
        "paleta": ["#001a33", "#003366", "#0080ff", "#00ffff"],
        "glow": "#00ffff",
        "bg": ["#001a33", "#003366", "#0080ff"],
        "tipografia": "Orbitron Bold",
        "ritmo": "24 cortes/min",
        "bpm": 108,
        "iluminacao": "Data stream · Luz holográfica",
        "enquadramento": "Close extremo",
        "cenas": CENAS_EPICO,
        "audio": {"tipo": "cyberpunk", "descricao": "Glitch eletrônico + voz sintetizada", "efeito": "Fascínio tecnológico"},
    },

    # ════════════════════════════════════════════════════════════════
    # 50 NOVOS PRESETS
    # ════════════════════════════════════════════════════════════════

    "drill": {
        "keywords": ["drill", "uk drill", "sombrio", "rua pesada"],
        "nome": "Drill Sombrio",
        "emocao": "Frieza · Tensão · Território",
        "paleta": ["#0a0a0a", "#1c1c1c", "#3a3a3a", "#7a0000"],
        "glow": "#7a0000",
        "bg": ["#0a0a0a", "#141414", "#1c1c1c"],
        "tipografia": "Anton",
        "ritmo": "28 cortes/min",
        "bpm": 142,
        "iluminacao": "Luz de poste · Sombra dura",
        "enquadramento": "Ângulo baixo",
        "cenas": CENAS_TENSO,
        "audio": {"tipo": "trap", "descricao": "808 deslizante + hi-hat triplo", "efeito": "Frieza e tensão territorial"},
    },
    "boombap": {
        "keywords": ["boom bap", "hip hop clássico", "old school", "vinil"],
        "nome": "Boom Bap Clássico",
        "emocao": "Autenticidade · Nostalgia · Raiz",
        "paleta": ["#2a1a0a", "#4a3018", "#8a5a2a", "#d4a857"],
        "glow": "#d4a857",
        "bg": ["#1a1208", "#2a1a0a", "#4a3018"],
        "tipografia": "Oswald Bold",
        "ritmo": "20 cortes/min",
        "bpm": 90,
        "iluminacao": "Luz de vinil quente · Grão de filme",
        "enquadramento": "Plano médio",
        "cenas": CENAS_COMERCIAL,
        "audio": {"tipo": "trap", "descricao": "Sample de vinil + kick seco", "efeito": "Nostalgia autêntica"},
    },
    "rnb_slow": {
        "keywords": ["r&b", "rnb", "slow jam", "sensual"],
        "nome": "R&B Slow Jam",
        "emocao": "Sensualidade · Intimidade · Calor",
        "paleta": ["#1a0014", "#4a0030", "#8a1a5a", "#e09bc7"],
        "glow": "#e09bc7",
        "bg": ["#1a0014", "#2a0a24", "#4a0030"],
        "tipografia": "Lora Italic",
        "ritmo": "10 cortes/min",
        "bpm": 68,
        "iluminacao": "Luz vermelha baixa · Sombra suave",
        "enquadramento": "Plano médio",
        "cenas": CENAS_INTIMISTA,
        "audio": {"tipo": "romance", "descricao": "Pad quente + groove de baixo lento", "efeito": "Sensualidade e proximidade"},
    },
    "funk_br": {
        "keywords": ["funk", "funk brasileiro", "baile", "passinho"],
        "nome": "Funk Brasileiro",
        "emocao": "Euforia · Comunidade · Calor Tropical",
        "paleta": ["#1a0a00", "#cc3300", "#ff6600", "#ffcc00"],
        "glow": "#ff6600",
        "bg": ["#1a0a00", "#3a1500", "#6a2800"],
        "tipografia": "Fredoka Bold",
        "ritmo": "30 cortes/min",
        "bpm": 130,
        "iluminacao": "Luz de baile · Refletor colorido",
        "enquadramento": "Ângulo baixo",
        "cenas": CENAS_ALTA_ENERGIA,
        "audio": {"tipo": "festa", "descricao": "Tamborzão + grave pesado", "efeito": "Euforia coletiva"},
    },
    "reggaeton": {
        "keywords": ["reggaeton", "perreo", "dembow", "latino"],
        "nome": "Reggaeton Quente",
        "emocao": "Sensualidade · Festa · Calor",
        "paleta": ["#330011", "#990033", "#ff3366", "#ffcc66"],
        "glow": "#ff3366",
        "bg": ["#220011", "#440022", "#660033"],
        "tipografia": "Poppins Black",
        "ritmo": "24 cortes/min",
        "bpm": 96,
        "iluminacao": "Luz neon rosa/laranja",
        "enquadramento": "Ângulo baixo",
        "cenas": CENAS_ALTA_ENERGIA,
        "audio": {"tipo": "eletronica", "descricao": "Dembow + sintetizador quente", "efeito": "Sensualidade festiva"},
    },
    "synthwave": {
        "keywords": ["synthwave", "outrun", "retrowave", "miami"],
        "nome": "Synthwave Outrun",
        "emocao": "Nostalgia · Velocidade · Neon",
        "paleta": ["#1a0033", "#ff2079", "#7b2fff", "#00e5ff"],
        "glow": "#ff2079",
        "bg": ["#1a0033", "#3a0a5a", "#7b2fff"],
        "tipografia": "Audiowide",
        "ritmo": "26 cortes/min",
        "bpm": 112,
        "iluminacao": "Grade de neon · Sol retrô",
        "enquadramento": "Travelling lateral",
        "cenas": CENAS_ALTA_ENERGIA,
        "audio": {"tipo": "cyberpunk", "descricao": "Arpejo de sintetizador analógico", "efeito": "Nostalgia futurista"},
    },
    "vaporwave": {
        "keywords": ["vaporwave", "aesthetic", "estátua", "pastel digital"],
        "nome": "Vaporwave Sonhador",
        "emocao": "Estranhamento · Nostalgia · Sonho",
        "paleta": ["#ff9ecb", "#a18cd1", "#fbc2eb", "#84fab0"],
        "glow": "#a18cd1",
        "bg": ["#2a1a3a", "#5a3a7a", "#a18cd1"],
        "tipografia": "Times New Roman Italic",
        "ritmo": "6 cortes/min",
        "bpm": 70,
        "iluminacao": "Luz pastel difusa · Névoa digital",
        "enquadramento": "Plano aberto",
        "cenas": CENAS_CONTEMPLATIVO,
        "audio": {"tipo": "ambient", "descricao": "Pad desacelerado + eco infinito", "efeito": "Dissociação onírica"},
    },
    "house": {
        "keywords": ["house", "house music", "deep house", "club"],
        "nome": "House Music Club",
        "emocao": "Groove · Liberdade · Movimento",
        "paleta": ["#000000", "#ff4d8d", "#4dd2ff", "#ffffff"],
        "glow": "#4dd2ff",
        "bg": ["#000000", "#0a0a1a", "#1a0a2a"],
        "tipografia": "Eurostile Bold",
        "ritmo": "30 cortes/min",
        "bpm": 124,
        "iluminacao": "Luz estroboscópica controlada",
        "enquadramento": "Travelling lateral",
        "cenas": CENAS_ALTA_ENERGIA,
        "audio": {"tipo": "eletronica", "descricao": "Four-on-the-floor + pluck synth", "efeito": "Groove contínuo"},
    },
    "techno": {
        "keywords": ["techno", "underground", "warehouse", "industrial"],
        "nome": "Techno Underground",
        "emocao": "Hipnose · Repetição · Intensidade",
        "paleta": ["#000000", "#1a1a1a", "#333333", "#ff0033"],
        "glow": "#ff0033",
        "bg": ["#000000", "#0a0a0a", "#1a1a1a"],
        "tipografia": "Space Mono Bold",
        "ritmo": "32 cortes/min",
        "bpm": 135,
        "iluminacao": "Luz estroboscópica industrial",
        "enquadramento": "Close extremo",
        "cenas": CENAS_ALTA_ENERGIA,
        "audio": {"tipo": "eletronica", "descricao": "Kick seco repetitivo + drone", "efeito": "Hipnose rítmica"},
    },
    "edm_festival": {
        "keywords": ["edm", "festival", "festival music", "main stage"],
        "nome": "EDM Festival",
        "emocao": "Euforia · Multidão · Clímax",
        "paleta": ["#000000", "#ff007a", "#00e0ff", "#ffe600"],
        "glow": "#00e0ff",
        "bg": ["#000000", "#0a0a1a", "#1a0a2a"],
        "tipografia": "Poppins Black",
        "ritmo": "36 cortes/min",
        "bpm": 128,
        "iluminacao": "Pirotecnia · Laser de palco",
        "enquadramento": "Grande angular",
        "cenas": CENAS_ALTA_ENERGIA,
        "audio": {"tipo": "eletronica", "descricao": "Build-up + drop com sub bass", "efeito": "Pico de euforia coletiva"},
    },
    "rock_classico": {
        "keywords": ["rock", "rock classico", "estrada", "guitarra"],
        "nome": "Rock Clássico de Estrada",
        "emocao": "Liberdade · Rebeldia · Energia Crua",
        "paleta": ["#1a1a1a", "#8B0000", "#cc6600", "#f0e68c"],
        "glow": "#cc6600",
        "bg": ["#1a1a1a", "#3a2a1a", "#5a3a1a"],
        "tipografia": "Oswald Black",
        "ritmo": "20 cortes/min",
        "bpm": 110,
        "iluminacao": "Luz de palco quente · Fumaça",
        "enquadramento": "Ângulo baixo",
        "cenas": CENAS_ALTA_ENERGIA,
        "audio": {"tipo": "rock", "descricao": "Power chords + bateria viva", "efeito": "Liberdade e energia crua"},
    },
    "punk": {
        "keywords": ["punk", "punk rock", "anarquia", "cru"],
        "nome": "Punk Rock Cru",
        "emocao": "Revolta · Urgência · Caos",
        "paleta": ["#000000", "#ff0033", "#ffffff", "#7a7a7a"],
        "glow": "#ff0033",
        "bg": ["#000000", "#0a0a0a", "#1a1a1a"],
        "tipografia": "Anton",
        "ritmo": "40 cortes/min",
        "bpm": 165,
        "iluminacao": "Luz de garagem · Flash dura",
        "enquadramento": "Close extremo",
        "cenas": CENAS_ALTA_ENERGIA,
        "audio": {"tipo": "rock", "descricao": "Power chords rápidos + bateria crua", "efeito": "Revolta imediata"},
    },
    "metal": {
        "keywords": ["metal", "heavy metal", "headbang", "pesado"],
        "nome": "Metal Pesado",
        "emocao": "Intensidade · Poder · Catarse",
        "paleta": ["#000000", "#1a1a1a", "#8B0000", "#c0c0c0"],
        "glow": "#c0c0c0",
        "bg": ["#000000", "#0a0a0a", "#1a1a1a"],
        "tipografia": "UnifrakturMaguntia",
        "ritmo": "34 cortes/min",
        "bpm": 150,
        "iluminacao": "Contraluz dura · Fumaça densa",
        "enquadramento": "Ângulo baixo",
        "cenas": CENAS_TENSO,
        "audio": {"tipo": "rock", "descricao": "Riff distorcido grave + double kick", "efeito": "Catarse intensa"},
    },
    "indie_alt": {
        "keywords": ["indie", "alternativo", "indie rock", "lo-fi guitar"],
        "nome": "Indie Alternativo",
        "emocao": "Autenticidade · Melancolia Suave · Sonho",
        "paleta": ["#1a1a2e", "#5a5a8a", "#a8a8d8", "#f0f0ff"],
        "glow": "#a8a8d8",
        "bg": ["#1a1a2e", "#3a3a5a", "#5a5a8a"],
        "tipografia": "Quicksand Medium",
        "ritmo": "14 cortes/min",
        "bpm": 92,
        "iluminacao": "Luz natural difusa · Janela",
        "enquadramento": "Plano médio",
        "cenas": CENAS_CONTEMPLATIVO,
        "audio": {"tipo": "rock", "descricao": "Guitarra reverberada + bateria leve", "efeito": "Melancolia suave"},
    },
    "grunge": {
        "keywords": ["grunge", "anos 90", "seattle", "alternativo sujo"],
        "nome": "Grunge 90s",
        "emocao": "Apatia · Tensão Contida · Autenticidade",
        "paleta": ["#1a1a14", "#4a3a2a", "#6a5a3a", "#9a8a6a"],
        "glow": "#9a8a6a",
        "bg": ["#1a1a14", "#2a2a1a", "#4a3a2a"],
        "tipografia": "Permanent Marker",
        "ritmo": "16 cortes/min",
        "bpm": 100,
        "iluminacao": "Luz suja de quarto · Fumaça de cigarro",
        "enquadramento": "Plano médio",
        "cenas": CENAS_TENSO,
        "audio": {"tipo": "rock", "descricao": "Guitarra fuzz + dinâmica quieto/alto", "efeito": "Tensão contida"},
    },
    "sertanejo_romantico": {
        "keywords": ["sertanejo romântico", "modão", "viola", "amor sertanejo"],
        "nome": "Sertanejo Romântico",
        "emocao": "Saudade · Amor · Simplicidade",
        "paleta": ["#2a1a00", "#5a3a10", "#a87830", "#f0d8a0"],
        "glow": "#a87830",
        "bg": ["#1a1000", "#2a1a00", "#5a3a10"],
        "tipografia": "Playfair Display Italic",
        "ritmo": "12 cortes/min",
        "bpm": 76,
        "iluminacao": "Pôr do sol no campo · Luz dourada",
        "enquadramento": "Plano aberto",
        "cenas": CENAS_INTIMISTA,
        "audio": {"tipo": "romance", "descricao": "Viola caipira + voz dupla", "efeito": "Saudade aconchegante"},
    },
    "sertanejo_festa": {
        "keywords": ["sertanejo universitário", "arrocha", "balada sertaneja"],
        "nome": "Sertanejo Universitário",
        "emocao": "Festa · Liberdade · Energia",
        "paleta": ["#1a0a00", "#cc5500", "#ff8800", "#ffe0a0"],
        "glow": "#ff8800",
        "bg": ["#1a0a00", "#3a1a00", "#6a3300"],
        "tipografia": "Bebas Neue",
        "ritmo": "26 cortes/min",
        "bpm": 130,
        "iluminacao": "Luz de arena · Refletores quentes",
        "enquadramento": "Ângulo baixo",
        "cenas": CENAS_ALTA_ENERGIA,
        "audio": {"tipo": "festa", "descricao": "Sanfona eletrônica + bateria de arena", "efeito": "Energia de festa"},
    },
    "pagode": {
        "keywords": ["pagode", "samba de mesa", "roda de samba", "quintal"],
        "nome": "Pagode de Quintal",
        "emocao": "Alegria · Comunidade · Aconchego",
        "paleta": ["#2a1500", "#8a5a1a", "#d4a040", "#fff0c0"],
        "glow": "#d4a040",
        "bg": ["#1a0d00", "#2a1500", "#5a3a10"],
        "tipografia": "Pacifico",
        "ritmo": "14 cortes/min",
        "bpm": 88,
        "iluminacao": "Luz de quintal · Tarde quente",
        "enquadramento": "Plano aberto",
        "cenas": CENAS_COMERCIAL,
        "audio": {"tipo": "festa", "descricao": "Pandeiro + cavaquinho", "efeito": "Alegria comunitária"},
    },
    "forro": {
        "keywords": ["forró", "pé de serra", "sanfona", "nordeste"],
        "nome": "Forró Pé de Serra",
        "emocao": "Festa · Tradição · Calor Nordestino",
        "paleta": ["#3a1500", "#cc6600", "#ffaa33", "#fff0d0"],
        "glow": "#ffaa33",
        "bg": ["#2a1000", "#3a1500", "#6a3300"],
        "tipografia": "Fredoka Bold",
        "ritmo": "22 cortes/min",
        "bpm": 118,
        "iluminacao": "Luz de festa junina · Fogueira",
        "enquadramento": "Plano aberto",
        "cenas": CENAS_COMERCIAL,
        "audio": {"tipo": "festa", "descricao": "Sanfona + zabumba + triângulo", "efeito": "Tradição calorosa"},
    },
    "axe": {
        "keywords": ["axé", "carnaval salvador", "litoral", "verão baiano"],
        "nome": "Axé Litoral",
        "emocao": "Euforia · Verão · Sensualidade",
        "paleta": ["#001a33", "#00aacc", "#ff8800", "#ffe066"],
        "glow": "#ff8800",
        "bg": ["#001a33", "#003355", "#0077aa"],
        "tipografia": "Baloo 2 Bold",
        "ritmo": "32 cortes/min",
        "bpm": 128,
        "iluminacao": "Sol forte de praia · Reflexo de água",
        "enquadramento": "Ângulo baixo",
        "cenas": CENAS_ALTA_ENERGIA,
        "audio": {"tipo": "festa", "descricao": "Percussão de trio elétrico", "efeito": "Euforia de verão"},
    },
    "samba": {
        "keywords": ["samba", "samba de raiz", "roda de samba", "escola de samba"],
        "nome": "Samba de Raiz",
        "emocao": "Paixão · Raiz · Celebração",
        "paleta": ["#1a0a00", "#8a1a1a", "#cc8800", "#fff0c0"],
        "glow": "#cc8800",
        "bg": ["#1a0a00", "#2a1500", "#4a2000"],
        "tipografia": "Lobster",
        "ritmo": "18 cortes/min",
        "bpm": 96,
        "iluminacao": "Luz de terreiro · Tons terrosos",
        "enquadramento": "Plano médio",
        "cenas": CENAS_COMERCIAL,
        "audio": {"tipo": "festa", "descricao": "Cavaquinho + surdo + pandeiro", "efeito": "Paixão e raiz"},
    },
    "folk_acustico": {
        "keywords": ["folk", "acústico", "campo", "violão simples"],
        "nome": "Folk Acústico",
        "emocao": "Simplicidade · Introspecção · Natureza",
        "paleta": ["#2a2410", "#5a4a20", "#9a8a50", "#e0d8b0"],
        "glow": "#9a8a50",
        "bg": ["#1a1808", "#2a2410", "#5a4a20"],
        "tipografia": "Caveat",
        "ritmo": "8 cortes/min",
        "bpm": 70,
        "iluminacao": "Luz natural de campo · Manhã",
        "enquadramento": "Plano aberto",
        "cenas": CENAS_CONTEMPLATIVO,
        "audio": {"tipo": "lofi", "descricao": "Violão fingerstyle + harmônica", "efeito": "Introspecção tranquila"},
    },
    "violao_voz": {
        "keywords": ["voz e violão", "acústico intimista", "voz solo"],
        "nome": "Voz e Violão",
        "emocao": "Vulnerabilidade · Intimidade · Verdade",
        "paleta": ["#1a1410", "#4a3a2a", "#8a7050", "#e0d0b0"],
        "glow": "#8a7050",
        "bg": ["#0a0808", "#1a1410", "#4a3a2a"],
        "tipografia": "Cormorant Garamond",
        "ritmo": "8 cortes/min",
        "bpm": 64,
        "iluminacao": "Spot único · Fundo escuro",
        "enquadramento": "Plano médio",
        "cenas": CENAS_INTIMISTA,
        "audio": {"tipo": "lofi", "descricao": "Violão nylon + voz próxima", "efeito": "Vulnerabilidade verdadeira"},
    },
    "bossa_nova": {
        "keywords": ["bossa nova", "ipanema", "samba jazz", "leve"],
        "nome": "Bossa Nova Intimista",
        "emocao": "Sofisticação · Leveza · Sedução Sutil",
        "paleta": ["#0a1a1a", "#1a4040", "#3a8080", "#cfe8e0"],
        "glow": "#3a8080",
        "bg": ["#0a1414", "#0a1a1a", "#1a4040"],
        "tipografia": "Cormorant Italic",
        "ritmo": "10 cortes/min",
        "bpm": 78,
        "iluminacao": "Luz de fim de tarde · Janela com vista mar",
        "enquadramento": "Plano médio",
        "cenas": CENAS_INTIMISTA,
        "audio": {"tipo": "lofi", "descricao": "Violão sincopado + brushes de bateria", "efeito": "Sedução sutil"},
    },
    "suspense_psicologico": {
        "keywords": ["suspense psicológico", "thriller mental", "tensão interna"],
        "nome": "Suspense Psicológico",
        "emocao": "Paranoia · Dúvida · Tensão Interna",
        "paleta": ["#0a0a0a", "#1a1a22", "#3a3a4a", "#7a7a8a"],
        "glow": "#7a7a8a",
        "bg": ["#0a0a0a", "#12121a", "#1a1a22"],
        "tipografia": "Special Elite",
        "ritmo": "16 cortes/min",
        "bpm": 82,
        "iluminacao": "Luz instável · Sombra que se move",
        "enquadramento": "Close extremo",
        "cenas": CENAS_TENSO,
        "audio": {"tipo": "noir", "descricao": "Drone dissonante + relógio distante", "efeito": "Paranoia crescente"},
    },
    "terror_sobrenatural": {
        "keywords": ["terror sobrenatural", "fantasma", "possessão", "demônio"],
        "nome": "Terror Sobrenatural",
        "emocao": "Pavor · Presença · Inevitabilidade",
        "paleta": ["#000000", "#0a0a14", "#1a0a2a", "#4a1a6a"],
        "glow": "#4a1a6a",
        "bg": ["#000000", "#05050a", "#0a0a14"],
        "tipografia": "Creepster",
        "ritmo": "22 cortes/min",
        "bpm": 100,
        "iluminacao": "Lanterna trêmula · Escuridão absoluta",
        "enquadramento": "Close extremo",
        "cenas": CENAS_TENSO,
        "audio": {"tipo": "noir", "descricao": "Drone grave + sussurros distantes", "efeito": "Pavor sobrenatural"},
    },
    "fantasia_epica": {
        "keywords": ["fantasia épica", "dragões", "reino", "magia"],
        "nome": "Fantasia Épica",
        "emocao": "Maravilha · Heroísmo · Destino",
        "paleta": ["#0a1a0a", "#1a4a2a", "#3a7a3a", "#d4af37"],
        "glow": "#d4af37",
        "bg": ["#0a1a0a", "#1a2a1a", "#2a4a2a"],
        "tipografia": "Cinzel Decorative",
        "ritmo": "16 cortes/min",
        "bpm": 86,
        "iluminacao": "Névoa mística · Raios de luz entre árvores",
        "enquadramento": "Grande angular",
        "cenas": CENAS_EPICO,
        "audio": {"tipo": "epic", "descricao": "Coral + cordas + harpa", "efeito": "Maravilha heroica"},
    },
    "drama_historico": {
        "keywords": ["drama histórico", "época", "guerra mundial", "biografia"],
        "nome": "Drama Histórico",
        "emocao": "Dignidade · Sacrifício · Memória",
        "paleta": ["#1a1408", "#4a3a1a", "#7a6030", "#cfc090"],
        "glow": "#7a6030",
        "bg": ["#1a1408", "#2a2010", "#4a3a1a"],
        "tipografia": "Cinzel Bold",
        "ritmo": "14 cortes/min",
        "bpm": 74,
        "iluminacao": "Luz de época · Sépia suave",
        "enquadramento": "Plano aberto",
        "cenas": CENAS_EPICO,
        "audio": {"tipo": "epic", "descricao": "Cordas solenes + percussão distante", "efeito": "Dignidade e memória"},
    },
    "meditacao": {
        "keywords": ["meditação", "mindfulness", "respiração", "presença"],
        "nome": "Meditação Guiada",
        "emocao": "Quietude · Presença · Centro",
        "paleta": ["#0a1418", "#1a3038", "#3a5a60", "#a8d8d0"],
        "glow": "#a8d8d0",
        "bg": ["#0a1418", "#102228", "#1a3038"],
        "tipografia": "Quicksand Light",
        "ritmo": "4 cortes/min",
        "bpm": 52,
        "iluminacao": "Luz suave de amanhecer",
        "enquadramento": "Plano aberto",
        "cenas": CENAS_CONTEMPLATIVO,
        "audio": {"tipo": "ambient", "descricao": "Drone respirado + sino tibetano", "efeito": "Quietude profunda"},
    },
    "gospel": {
        "keywords": ["gospel", "louvor", "igreja", "fé"],
        "nome": "Gospel & Louvor",
        "emocao": "Fé · Elevação · Esperança",
        "paleta": ["#1a1400", "#5a4500", "#d4af37", "#fff8e0"],
        "glow": "#d4af37",
        "bg": ["#1a1400", "#2a2000", "#5a4500"],
        "tipografia": "Playfair Display Black",
        "ritmo": "14 cortes/min",
        "bpm": 82,
        "iluminacao": "Luz vinda de cima · Vitral colorido",
        "enquadramento": "Grande angular",
        "cenas": CENAS_EPICO,
        "audio": {"tipo": "epic", "descricao": "Coral + órgão + palmas", "efeito": "Elevação espiritual"},
    },
    "espiritual_zen": {
        "keywords": ["zen", "contemplativo", "minimalismo espiritual", "vazio"],
        "nome": "Zen Contemplativo",
        "emocao": "Vazio · Serenidade · Presença",
        "paleta": ["#101010", "#2a2a28", "#5a5a50", "#e8e4d8"],
        "glow": "#e8e4d8",
        "bg": ["#101010", "#181818", "#2a2a28"],
        "tipografia": "EB Garamond",
        "ritmo": "4 cortes/min",
        "bpm": 50,
        "iluminacao": "Luz difusa neutra · Papel de arroz",
        "enquadramento": "Plano aberto",
        "cenas": CENAS_CONTEMPLATIVO,
        "audio": {"tipo": "ambient", "descricao": "Silêncio + tigela de cristal", "efeito": "Serenidade absoluta"},
    },
    "vlog_diario": {
        "keywords": ["vlog", "dia a dia", "rotina", "lifestyle casual"],
        "nome": "Vlog do Dia a Dia",
        "emocao": "Autenticidade · Leveza · Conexão",
        "paleta": ["#fff4e0", "#ffd9a0", "#ff9d6c", "#5a4a3a"],
        "glow": "#ff9d6c",
        "bg": ["#3a2a1a", "#6a4a30", "#ffd9a0"],
        "tipografia": "Poppins Medium",
        "ritmo": "18 cortes/min",
        "bpm": 100,
        "iluminacao": "Luz natural de janela",
        "enquadramento": "Plano médio",
        "cenas": CENAS_CONTEMPLATIVO,
        "audio": {"tipo": "lofi", "descricao": "Beat lo-fi casual + ukulele", "efeito": "Leveza cotidiana"},
    },
    "motivacional": {
        "keywords": ["motivacional", "discurso", "corporativo inspirador", "superação pessoal"],
        "nome": "Motivacional Corporativo",
        "emocao": "Determinação · Foco · Superação",
        "paleta": ["#0a0a0a", "#1a2a3a", "#2a6ab0", "#ffffff"],
        "glow": "#2a6ab0",
        "bg": ["#0a0a0a", "#0a1420", "#1a2a3a"],
        "tipografia": "Montserrat Black",
        "ritmo": "16 cortes/min",
        "bpm": 90,
        "iluminacao": "Luz de palco TED · Contraste forte",
        "enquadramento": "Ângulo baixo",
        "cenas": CENAS_EPICO,
        "audio": {"tipo": "epic", "descricao": "Build orquestral progressivo", "efeito": "Determinação crescente"},
    },
    "aventura": {
        "keywords": ["aventura", "trilha", "expedição", "montanha"],
        "nome": "Aventura & Trilha",
        "emocao": "Coragem · Descoberta · Vastidão",
        "paleta": ["#0a1a2a", "#1a4a5a", "#5a9a6a", "#e0d090"],
        "glow": "#5a9a6a",
        "bg": ["#0a1a2a", "#1a3a4a", "#1a4a5a"],
        "tipografia": "Bebas Neue",
        "ritmo": "18 cortes/min",
        "bpm": 104,
        "iluminacao": "Luz de amanhecer na montanha",
        "enquadramento": "Grande angular",
        "cenas": CENAS_EPICO,
        "audio": {"tipo": "rock", "descricao": "Percussão tribal + guitarra aberta", "efeito": "Coragem expansiva"},
    },
    "esportivo_radical": {
        "keywords": ["esporte radical", "skate", "surf", "adrenalina extrema"],
        "nome": "Esportivo Radical",
        "emocao": "Adrenalina · Risco · Liberdade",
        "paleta": ["#001020", "#0a3a5a", "#ff5500", "#ffffff"],
        "glow": "#ff5500",
        "bg": ["#001020", "#012640", "#0a3a5a"],
        "tipografia": "Anton",
        "ritmo": "32 cortes/min",
        "bpm": 138,
        "iluminacao": "Sol forte · Contraluz de ação",
        "enquadramento": "Travelling lateral",
        "cenas": CENAS_ALTA_ENERGIA,
        "audio": {"tipo": "rock", "descricao": "Guitarra distorcida + bateria acelerada", "efeito": "Adrenalina de risco"},
    },
    "luxury_lifestyle": {
        "keywords": ["luxury lifestyle", "alto padrão", "ostentação elegante", "jato particular"],
        "nome": "Luxury Lifestyle",
        "emocao": "Exclusividade · Conquista · Refinamento",
        "paleta": ["#0a0805", "#3a2a10", "#C8860A", "#F5E8C8"],
        "glow": "#C8860A",
        "bg": ["#0a0805", "#1a1408", "#3a2a10"],
        "tipografia": "Didot Bold",
        "ritmo": "14 cortes/min",
        "bpm": 84,
        "iluminacao": "Luz de hotel cinco estrelas",
        "enquadramento": "Macro extremo",
        "cenas": CENAS_COMERCIAL,
        "audio": {"tipo": "trap", "descricao": "Piano de luxo + sub bass discreto", "efeito": "Sensação de conquista"},
    },
    "unboxing_tech": {
        "keywords": ["unboxing", "tech review", "gadget", "produto eletrônico"],
        "nome": "Unboxing Tech",
        "emocao": "Curiosidade · Precisão · Modernidade",
        "paleta": ["#0a0a0c", "#1a1a22", "#3a6aff", "#e8eaf0"],
        "glow": "#3a6aff",
        "bg": ["#0a0a0c", "#10101a", "#1a1a22"],
        "tipografia": "Orbitron",
        "ritmo": "20 cortes/min",
        "bpm": 100,
        "iluminacao": "Luz de softbox · Reflexo de produto",
        "enquadramento": "Macro extremo",
        "cenas": CENAS_COMERCIAL,
        "audio": {"tipo": "cyberpunk", "descricao": "Clique digital + synth limpo", "efeito": "Curiosidade tecnológica"},
    },
    "beleza_skincare": {
        "keywords": ["beleza", "skincare", "cosméticos", "cuidado da pele"],
        "nome": "Beleza & Skincare",
        "emocao": "Cuidado · Pureza · Autoestima",
        "paleta": ["#fff5f0", "#ffd9cc", "#ff9b85", "#7a4a3a"],
        "glow": "#ff9b85",
        "bg": ["#3a2018", "#6a3a2a", "#ffd9cc"],
        "tipografia": "Quicksand Bold",
        "ritmo": "10 cortes/min",
        "bpm": 74,
        "iluminacao": "Luz difusa de beauty dish",
        "enquadramento": "Macro extremo",
        "cenas": CENAS_COMERCIAL,
        "audio": {"tipo": "ambient", "descricao": "Pad cristalino + leve percussão", "efeito": "Cuidado e pureza"},
    },
    "moda_editorial": {
        "keywords": ["moda editorial sleek", "vogue minimalista", "alta costura"],
        "nome": "Moda Editorial Sleek",
        "emocao": "Atitude · Vanguarda · Precisão",
        "paleta": ["#0a0a0a", "#2a2a2a", "#c0c0c0", "#ffffff"],
        "glow": "#c0c0c0",
        "bg": ["#0a0a0a", "#1a1a1a", "#2a2a2a"],
        "tipografia": "Bodoni Moda",
        "ritmo": "18 cortes/min",
        "bpm": 96,
        "iluminacao": "Luz dura de estúdio · Sombra geométrica",
        "enquadramento": "Plano médio",
        "cenas": CENAS_COMERCIAL,
        "audio": {"tipo": "eletronica", "descricao": "Synth minimal + clap seco", "efeito": "Vanguarda precisa"},
    },
    "culinaria_gourmet": {
        "keywords": ["culinária gourmet", "fine dining", "chef autoral", "receita"],
        "nome": "Culinária Gourmet",
        "emocao": "Prazer · Arte · Cuidado",
        "paleta": ["#1a0f00", "#4a2a10", "#b87333", "#f4e0c0"],
        "glow": "#b87333",
        "bg": ["#1a0f00", "#2a1808", "#4a2a10"],
        "tipografia": "Playfair Display Italic",
        "ritmo": "10 cortes/min",
        "bpm": 68,
        "iluminacao": "Luz lateral quente · Vapor sutil",
        "enquadramento": "Macro extremo",
        "cenas": CENAS_COMERCIAL,
        "audio": {"tipo": "lofi", "descricao": "Piano suave + textura de cozinha", "efeito": "Prazer artesanal"},
    },
    "carnaval": {
        "keywords": ["carnaval", "carnaval de rua", "bloco", "folia"],
        "nome": "Carnaval de Rua",
        "emocao": "Euforia · Liberdade · Folia",
        "paleta": ["#330033", "#ff0066", "#ffcc00", "#00cc99"],
        "glow": "#ff0066",
        "bg": ["#1a0020", "#330033", "#5a0050"],
        "tipografia": "Baloo 2 Black",
        "ritmo": "34 cortes/min",
        "bpm": 130,
        "iluminacao": "Confete · Luz de rua colorida",
        "enquadramento": "Grande angular",
        "cenas": CENAS_ALTA_ENERGIA,
        "audio": {"tipo": "festa", "descricao": "Bateria de bloco + metais", "efeito": "Euforia coletiva máxima"},
    },
    "festa_junina": {
        "keywords": ["festa junina", "são joão", "fogueira", "quadrilha"],
        "nome": "Festa Junina",
        "emocao": "Alegria · Tradição · Calor de Fogueira",
        "paleta": ["#1a0a00", "#cc6600", "#ffaa00", "#fff0c0"],
        "glow": "#ffaa00",
        "bg": ["#0d0500", "#1a0a00", "#3a1500"],
        "tipografia": "Fredoka Bold",
        "ritmo": "20 cortes/min",
        "bpm": 110,
        "iluminacao": "Luz de fogueira · Lanternas",
        "enquadramento": "Plano aberto",
        "cenas": CENAS_COMERCIAL,
        "audio": {"tipo": "festa", "descricao": "Sanfona + viola caipira animada", "efeito": "Alegria tradicional"},
    },
    "natal_aconchegante": {
        "keywords": ["natal", "natal aconchegante", "lareira", "neve fofa"],
        "nome": "Natal Aconchegante",
        "emocao": "Aconchego · Família · Calor Doméstico",
        "paleta": ["#1a0a0a", "#5a1a1a", "#0a4a2a", "#d4af37"],
        "glow": "#d4af37",
        "bg": ["#1a0a0a", "#2a1010", "#3a1a1a"],
        "tipografia": "Mountains of Christmas",
        "ritmo": "8 cortes/min",
        "bpm": 66,
        "iluminacao": "Luz de lareira · Pisca-pisca quente",
        "enquadramento": "Plano médio",
        "cenas": CENAS_INTIMISTA,
        "audio": {"tipo": "lofi", "descricao": "Sininhos + piano aconchegante", "efeito": "Aconchego familiar"},
    },
    "ano_novo": {
        "keywords": ["ano novo", "réveillon", "fogos de artifício", "contagem regressiva"],
        "nome": "Réveillon & Fogos",
        "emocao": "Esperança · Celebração · Renovação",
        "paleta": ["#000010", "#1a1a4a", "#d4af37", "#ffffff"],
        "glow": "#d4af37",
        "bg": ["#000010", "#0a0a2a", "#1a1a4a"],
        "tipografia": "Bebas Neue",
        "ritmo": "28 cortes/min",
        "bpm": 124,
        "iluminacao": "Fogos de artifício · Brilho dourado",
        "enquadramento": "Grande angular",
        "cenas": CENAS_ALTA_ENERGIA,
        "audio": {"tipo": "eletronica", "descricao": "Build de contagem + explosão festiva", "efeito": "Esperança celebrativa"},
    },
    "casamento_classico": {
        "keywords": ["casamento clássico", "cerimônia tradicional", "altar"],
        "nome": "Casamento Clássico",
        "emocao": "Solenidade · Amor · Tradição",
        "paleta": ["#fffaf5", "#f0e0d0", "#d4af37", "#3a2a1a"],
        "glow": "#d4af37",
        "bg": ["#2a2018", "#5a4a3a", "#f0e0d0"],
        "tipografia": "Great Vibes",
        "ritmo": "6 cortes/min",
        "bpm": 64,
        "iluminacao": "Luz de igreja · Vitral dourado",
        "enquadramento": "Plano aberto",
        "cenas": CENAS_INTIMISTA,
        "audio": {"tipo": "romance", "descricao": "Órgão + cordas solenes", "efeito": "Solenidade emocionada"},
    },
    "afrobeat": {
        "keywords": ["afrobeat", "africano", "percussão tribal", "amapiano"],
        "nome": "Afrobeat Vibrante",
        "emocao": "Vitalidade · Comunidade · Ritmo Ancestral",
        "paleta": ["#1a0a00", "#cc4400", "#ffaa00", "#00aa55"],
        "glow": "#ffaa00",
        "bg": ["#1a0a00", "#3a1500", "#5a2800"],
        "tipografia": "Baloo 2 Bold",
        "ritmo": "24 cortes/min",
        "bpm": 112,
        "iluminacao": "Sol forte · Tons terrosos",
        "enquadramento": "Ângulo baixo",
        "cenas": CENAS_ALTA_ENERGIA,
        "audio": {"tipo": "festa", "descricao": "Percussão polirrítmica + baixo log drum", "efeito": "Vitalidade ancestral"},
    },
    "nostalgia_anos80": {
        "keywords": ["nostalgia anos 80", "vhs", "fita cassete", "retro tech"],
        "nome": "Nostalgia Anos 80",
        "emocao": "Nostalgia · Inocência · Brilho Artificial",
        "paleta": ["#1a0033", "#ff3399", "#33ccff", "#ffff66"],
        "glow": "#ff3399",
        "bg": ["#1a0033", "#2a0a4a", "#3a0a6a"],
        "tipografia": "Press Start 2P",
        "ritmo": "22 cortes/min",
        "bpm": 108,
        "iluminacao": "Brilho de VHS · Linhas de escaneamento",
        "enquadramento": "Plano médio",
        "cenas": CENAS_ALTA_ENERGIA,
        "audio": {"tipo": "cyberpunk", "descricao": "Synth-pop vintage + caixa de ritmo", "efeito": "Nostalgia luminosa"},
    },
    "dark_academia": {
        "keywords": ["dark academia", "biblioteca antiga", "acadêmico sombrio", "outono"],
        "nome": "Dark Academia",
        "emocao": "Melancolia Intelectual · Mistério · Erudição",
        "paleta": ["#1a1408", "#3a2a14", "#6a4a24", "#c0a868"],
        "glow": "#c0a868",
        "bg": ["#0d0a05", "#1a1408", "#2a2010"],
        "tipografia": "EB Garamond Italic",
        "ritmo": "10 cortes/min",
        "bpm": 70,
        "iluminacao": "Luz de vela · Janela gótica",
        "enquadramento": "Plano médio",
        "cenas": CENAS_TENSO,
        "audio": {"tipo": "lofi", "descricao": "Violino melancólico + páginas virando", "efeito": "Melancolia intelectual"},
    },
    "gulf_futurism": {
        "keywords": ["futurismo do golfo", "arab futurism", "dubai futurista", "skyline dourado"],
        "nome": "Futurismo do Golfo",
        "emocao": "Visão · Opulência · Velocidade Civilizacional",
        "paleta": ["#0a0805", "#1a1410", "#C9A227", "#00C2D1"],
        "glow": "#C9A227",
        "bg": ["#0a0805", "#141008", "#1a1410"],
        "tipografia": "Cairo Bold",
        "ritmo": "16 cortes/min",
        "bpm": 92,
        "iluminacao": "Skyline noturno · Reflexo dourado em vidro",
        "enquadramento": "Grande angular",
        "cenas": CENAS_EPICO,
        "audio": {"tipo": "ambient", "descricao": "Pad sintético + oud processado", "efeito": "Visão e opulência"},
    },
    "caligrafia_neon": {
        "keywords": ["caligrafia neon", "kufi futurista", "geometria árabe neon"],
        "nome": "Caligrafia Neon",
        "emocao": "Identidade · Modernidade · Tradição Reinventada",
        "paleta": ["#05080a", "#0d1418", "#00C2D1", "#C9A227"],
        "glow": "#00C2D1",
        "bg": ["#05080a", "#0a1014", "#0d1418"],
        "tipografia": "Reem Kufi",
        "ritmo": "18 cortes/min",
        "bpm": 98,
        "iluminacao": "Linhas de neon geométricas · Contraluz",
        "enquadramento": "Close extremo",
        "cenas": CENAS_ALTA_ENERGIA,
        "audio": {"tipo": "cyberpunk", "descricao": "Synth modular + percussão de oud eletrônico", "efeito": "Tradição reinventada"},
    },
}